name: Release CI

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            name: linux
            suffix: ''
          - target: x86_64-apple-darwin
            os: macos-latest
            name: macos
            suffix: ''
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            name: windows
            suffix: .exe

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3.5.0

      - uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - uses: actions/cache@v3.3.1
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions/cache@v3.3.1
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-git-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions/cache@v3.3.1
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions-rs/cargo@v1.0.1
        with:
          command: build
          args: '--release'

      - name: Package
        shell: bash
        run: |
          cd target/release
          tar czvf ../../pass3d-pool-${{ matrix.name }}.tar.gz pass3d-pool${{ matrix.suffix }}
          cd -

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "pass3d-pool-*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
